### ISSUE TITLE
Should not be focusable when disabled and should publish disabled attr

### ISSUE THREAD

**Issue by johnheroy** [Polymer/core-icon-button#13] opened 2015-04-06 22:31 UTC
Controls (native HTML `button` for which we should emulate behavior?) should not be tabbable / focusable when they are disabled per W3C spec [1]. See related for `core-menu-button` [2]

[1] http://www.w3.org/TR/1998/REC-html40-19980424/interact/forms.html#adef-disabled
[2] https://github.com/Polymer/core-menu-button/issues/17

**Comment by dplassgit** [comment] 2015-04-20 17:22
I think this is a dupe of #8

**Closed** 2015-04-22 21:40 UTC
